. e Added code to run install tests.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -125,13 +125,11 @@ jobs:
         if: always()
         uses: actions/upload-artifact@v7
         with:
-          name: vipm-settings-${{ env.LABVIEW_IMAGE }}
+          name: test_and_build_settings
           path: |
             /usr/local/jki/vipm/Settings.ini
             /root/natinst/.config/LabVIEW-${LABVIEW_VERSION_YEAR}/labview*
-            /tmp/nisvcloc.log
             /tmp/xvfb.log
-            /tmp/lunit-extensions-hang-*.png
 
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@v6
@@ -216,7 +214,38 @@ jobs:
           vipm install "${package}" astemes_lib_lunit jki_lib_caraya
 
       - name: VIPM List Installed Packages
-        run: vipm list --installed || true # or true for core dump
+        run: vipm list --installed
+
+      - name: Install Tests
+        run: |
+          ./scripts/create_install_tests.sh
+          ./scripts/run_install_tests.sh
+
+      - name: Upload VIPM and LabVIEW Settings as Artifacts (debugging)
+        if: always()
+        uses: actions/upload-artifact@v7
+        with:
+          name: test_and_build_settings
+          path: |
+            /usr/local/jki/vipm/Settings.ini
+            /root/natinst/.config/LabVIEW-${LABVIEW_VERSION_YEAR}/labview*
+            /tmp/xvfb.log
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v6
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: 'reports/*InstallTestReport.xml'
+          include_passed: true
+          
+      - name: Grab Artifacts
+        if: success() || failure() # always run even if the previous step fails
+        uses: actions/upload-artifact@v6
+        with:
+          name: post-install-test-reports 
+          path: |
+            reports
+            **/*.received.*
 
    
   PylaviChecks_on_Build:
