. e replaced echo with lunit tests and grabbed reports as artifacts and and published test results.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -184,8 +184,8 @@ jobs:
       - name: Test G-CLI
         run: |
           source setup-display.sh
-          ls "/usr/local/natinst/LabVIEW-2026-64/vi.lib/G CLI Tools"
-          ./bin/g-cli Echo -- "Hello World"
+          mkdir -p reports
+          ./bin/g-cli --timeout 300000 lunit -- r "reports/Lunit.UnitTestReport.xml" "Approval Testing.lvproj"
       - name: VIPM Build Package
         run: |
           source setup-display.sh
@@ -210,3 +210,17 @@ jobs:
           path: |
             /usr/local/jki/vipm/Settings.ini
             /root/natinst/.config/LabVIEW-${LABVIEW_VERSION_YEAR}/labview*
+
+      - name: Upload Test Results as Artifacts
+        if: always() 
+        uses: actions/upload-artifact@v7
+        with:
+          name: test_results-${{ env.LABVIEW_IMAGE }}
+          path: |
+            reports/*
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v6
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: 'reports/*.xml'
