. e Fixed indentation.

diff --git a/.github/workflows/test_and_build_docker.yml b/.github/workflows/test_and_build_docker.yml
--- a/.github/workflows/test_and_build_docker.yml
+++ b/.github/workflows/test_and_build_docker.yml
@@ -49,12 +49,12 @@ jobs:
       - name: Run Error Propagation Tests
         shell: bash
         run: |
-        for i in 1 2 3; do
-          g-cli Caraya -- -s "Tests/Error.Propagation.Tests/Error.Propagation.Tests.lvclass" -x "reports/Error.Propagation.UnitTestReport.xml" && break
-          echo "Attemept $i failed, retrying..."
-          pkill labview || true
-          sleep 10
-        done
+          for i in 1 2 3; do
+            g-cli Caraya -- -s "Tests/Error.Propagation.Tests/Error.Propagation.Tests.lvclass" -x "reports/Error.Propagation.UnitTestReport.xml" && break
+            echo "Attemept $i failed, retrying..."
+            pkill labview || true
+            sleep 10
+          done
 
       - name: Build Package
         shell: bash
