. e Added more version info for debugging and fixed typo.

diff --git a/.github/workflows/test_and_build_docker.yml b/.github/workflows/test_and_build_docker.yml
--- a/.github/workflows/test_and_build_docker.yml
+++ b/.github/workflows/test_and_build_docker.yml
@@ -23,8 +23,13 @@ jobs:
       - uses: actions/checkout@v6
         with:
           submodules: 'true'
-      - name: Check activation
-        run: vipm about
+      - name: Check Versions
+        run: |
+          cat /etc/os-os-release
+          dpkg -l | grep labview
+          vipm about
+          g-cli --version
+          git --version
       - name: Refresh package list
         run: vipm package-list-refresh
       - name: Install project dependencies
@@ -54,7 +59,7 @@ jobs:
         run: ./scripts/run_install_tests.sh
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@v6
-        if: success300000() || failure() # always run even if the previous step fails
+        if: success() || failure() # always run even if the previous step fails
         with:
           report_paths: 'reports/*.xml'
       - name: Grab Artifacts
