Moved Test outside of script to see if that makes difference.

diff --git a/.github/workflows/test_and_build_docker.yml b/.github/workflows/test_and_build_docker.yml
--- a/.github/workflows/test_and_build_docker.yml
+++ b/.github/workflows/test_and_build_docker.yml
@@ -23,8 +23,6 @@ jobs:
       - uses: actions/checkout@v6
         with:
           submodules: 'true'
-      - name: Pre-warm LabVIEW
-        run: labview64 &
       - name: Check activation
         run: vipm about
       - name: Refresh package list
@@ -33,9 +31,15 @@ jobs:
         run: vipm install approvals-dev.vipc
       - name: List installed packages
         run: vipm list --installed
-      - name: Run Unit Tests
+      - name: Run Caraya Extension Tests
         shell: bash
-        run: ./scripts/run_unittests.sh
+        run: g-cli Caraya -- -s "Tests/Caraya.Tests/Caraya Extension Tests/Caraya Extension Tests.lvclass" -x "reports/Caraya.UnitTestReport.xml"
+      - name: Run LUnit Extension Tests
+        shell: bash
+        run: g-cli lunit -- -r "reports/LUnit.UnitTestReport.xml" "Approval Testing.lvproj"
+      - name: Run Error Propagation Tests
+        shell: bash
+        run: g-cli Caraya -- -s "Tests/Error.Propagation.Tests/Error.Propagation.Tests.lvclass" -x "reports/Error.Propagation.UnitTestReport.xml"
       - name: Build Package
         shell: bash
         run: ./scripts/build.sh $GITHUB_RUN_NUMBER  
@@ -50,7 +54,7 @@ jobs:
         run: ./scripts/run_install_tests.sh
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@v6
-        if: success() || failure() # always run even if the previous step fails
+        if: success300000() || failure() # always run even if the previous step fails
         with:
           report_paths: 'reports/*.xml'
       - name: Grab Artifacts
