. e edited to go for fewer attempts to launch LV and disabled error output so it should continue on and now capture VIPM-CLI error logs

diff --git a/.github/workflows/test_and_build_docker.yml b/.github/workflows/test_and_build_docker.yml
--- a/.github/workflows/test_and_build_docker.yml
+++ b/.github/workflows/test_and_build_docker.yml
@@ -64,7 +64,7 @@ jobs:
           pkill -f g-cli || true
           pkill -f labview || true
           apt-get install -y lsof
-          for i in {1..10}; do
+          for i in {1..3}; do
             echo "Attempt $i: launching LabVIEW..."
             nohup labview64 > /tmp/lv_launch.log 2>&1 &
             LV_PID=$!
@@ -83,10 +83,10 @@ jobs:
             echo "VI server not detected on attempt $i, killing LabVIEW and retrying..."
             pkill -f labview64 || true
             sleep 5
-            if [ $i -eq 10 ]; then
-              echo "VI server failed to come up after 10 attempts"
-              exit 1
-            fi
+            # if [ $i -eq 10 ]; then
+            #   echo "VI server failed to come up after 10 attempts"
+            #   exit 1
+            # fi
           done
       - name: Build Package
         shell: bash
@@ -119,7 +119,8 @@ jobs:
           path: |
             reports
             **/*.received.*
-      - name: Grab Artifacts
+            /usr/local/jki/vipm/VIPM-CLI/error    
+        - name: Grab Artifacts
         if: success() || failure() # always run even if the previous step fails
         uses: actions/upload-artifact@v6
         with:
